# Based on https://github.com/PrakashTrove/AWS-CodeBuild-NetCore/blob/master/buildspec.yml
# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy
version: 0.2
    
phases:   
  install:
    runtime-versions:
      dotnet: latest
      
  pre_build:
    commands:
      - echo Restore started on `date`
      - cd ./service/src/BachBetV2.WebApi
      - dir
      - dotnet restore BachBetV2.WebApi.csproj
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build BachBetV2.WebApi.csproj
      
  post_build:
    commands:
      - echo Publish started on `date`
      # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/dotnet-linux-platform-bundle-app.html
      - dotnet publish -c Release -r linux-x64 --self-contained false BachBetV2.WebApi.csproj
      
artifacts:
  files:
    - '**/*'
  base-directory: ./service/src/BachBetV2.WebApi/bin/Release/net6.0/linux-x64/publish
  discard-paths: no
  name: bachbetv2-service-$CODEBUILD_BUILD_NUMBER